name: Docker Build and Push

on:
  push:
    branches:
      - feature/docker_images

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment:
      name: dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to AWS ECR
        run: |
          aws --version
          aws ecr get-login-password --region us0-east-1 | docker login --username AWS --password-stdin 762407495953.dkr.ecr.us-east-1.amazonaws.com

      - name: Frontend docker build & push
        env:
          ECR_REPOSITORY: "kingsley-devops-excercise"
          IMAGE_TAG: "latest"
        run: |
          cd front
          docker build -t $ECR_REPOSITORY$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG 762407495953.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push 762407495953.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

