name: Docker Build and Push

on:
  push:
    branches:
      - feature/docker_images

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment:
      name: dev

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Frontend docker build & push
        env:
          DOCKER_REPOSITORY: "dominionsystemsinc/frontend-devops-exercise"
          IMAGE_TAG: "latest"
        run: |
          cd front
          docker build -t $DOCKER_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_REPOSITORY:$IMAGE_TAG
      
      - name: Backend docker build & push
        env:
          DOCKER_REPOSITORY: "dominionsystemsinc/backend-devops-exercise"
          IMAGE_TAG: "latest"
        run: |
          cd back
          docker build -t $DOCKER_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_REPOSITORY:$IMAGE_TAG
